name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-east1-docker.pkg.dev --quiet

    - name: Build and Push Docker Image to Artifact Registry
      run: |
        IMAGE="asia-east1-docker.pkg.dev/genuine-flight-462611-t5/cloudrun-repo/my-cloudrun-service"
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        IMAGE="asia-east1-docker.pkg.dev/genuine-flight-462611-t5/cloudrun-repo/my-cloudrun-service"
        gcloud run deploy my-cloudrun-service \
          --image=$IMAGE \
          --region=asia-east1 \
          --platform=managed \
          --allow-unauthenticated \
          --quiet
